name: "Validate YYYYMMDD input"

inputs:
  date:
    description: "Date: YYYYMMDD"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate release date
      uses: actions/github-script@v7
      with:
        script: |
          const dateStr = "${{inputs.date}}";
          if (!/^(\d){8}$/.test(dateStr)) {
            core.setFailed(`invalid date format yyyymmdd: ${dateStr}`)
          }
          const y = dateStr.substr(0,4), m = dateStr.substr(4,2) - 1, d = dateStr.substr(6,2);
          const date = new Date(y, m, d);
          if (isNaN(date.getDate())) {
            core.setFailed(`invalid date format yyyymmdd: ${dateStr}`);
          }
          const dy = date.getFullYear(), dm = ("00" + (date.getMonth()+1)).slice(-2), dd = ("00" + (date.getDate())).slice(-2);
          if (dateStr !== dy+dm+dd) {
            core.setFailed(`invalid date format yyyymmdd: ${dateStr}`);
          }
