name: "Create Release PR Body"

inputs:
  pr-list-path:
    description: "Path to the PR list file formatted --pretty=%an|%s"
    required: true
outputs:
  body:
    description: "PR body"
    value: ${{ steps.create-pr-body.outputs.prBody }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: "${{ github.action_path }}/go.mod"
        cache-dependency-path: "${{ github.action_path }}/go.sum"
    - run: |
        cp ${{ inputs.pr-list-path }} ${{ github.action_path }}/pr-list.txt
    - id: create-pr-body
      run: |
        echo "prBody<<EOF" >> $GITHUB_OUTPUT
        go run ./main.go createReleasePrBody pr-list.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ github.action_path }}
