name: Comment on Merged PR to Release Branch

on:
  pull_request:
    types: [closed]

jobs:
  comment_on_merge:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Merged PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;
            const commentBody = `- [ ] #${prNumber} by ${author}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
