name: Comment Merge PR to Release

on:
  pull_request:
    types: [closed]

jobs:
  comment_merge_pr_to_release:
    if: startsWith(github.event.pull_request.head.ref, 'release/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;
            const commentBody = `- [ ] #${prNumber} by ${author}: ${prTitle}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
