name: Create Release PRs
on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: "リリース日 YYYYMMDD"
        required: true
      title:
        description: "PRのタイトル"
        required: true

jobs:
  create_release_prs:
    name: Create Release Branch and PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: "develop"

      - name: Validate release date
        id: validate
        run: |
          releaseDate="${{ github.event.inputs.releaseDate }}"
          if ! date -d "$releaseDate" +%Y%m%d &>/dev/null; then
            echo "Invalid release date: $releaseDate"
            exit 1
          fi

      - name: Create release branch
        run: |
          releaseBranch="release/${{ github.event.inputs.releaseDate }}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name  "[bot] ${GITHUB_ACTOR}"
          git checkout -b "$releaseBranch"
          git commit --allow-empty -m "[release] empty commit for $releaseBranch"
          git push origin "$releaseBranch"
          echo "RELEASE_BRANCH=$releaseBranch" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
      - name: create release pr
        run: |
          gh pr create -B main -t ${{ steps.github.event.inputs.title }} -b ${{ steps.create-release-pr-body.outputs.report }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: create release to develop
        run: |
          gh pr create -B develop -t "[Release to Develop]: ${{ steps.github.event.inputs.title }}" -b ${{ steps.create-release-pr-body.outputs.report }}
        env:
          GH_TOKEN: ${{ github.token }}
