name: Create Release/Hotfix Branch

on:
  workflow_call:
    inputs:
      releaseType:
        description: "release or hotfix"
        required: true
        type: string
      releaseDate:
        description: "Release Date: YYYYMMDD"
        required: true
        type: string
      title:
        description: "PR Title"
        required: true
        type: string
      repository:
        description: "${{ github.repository }}"
        required: true
        type: string
      sourceBranch:
        description: "develop or main"
        required: true
        type: string
    outputs:
      branch:
        description: "Release/Hotfix Branch Name"
        value: ${{ jobs.create_release.outputs.body }}

jobs:
  create_branch:
    name: Create Branch
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.create-branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.sourceBranch }}

      - name: Validate release type
        uses: actions/github-script@v7
        with:
          script: |
            if (${{inputs.releaseType}} !== "release" && ${{inputs.releaseType}} !== "hotfix") {
              core.setFailed(`invalid release type: ${{inputs.releaseType}}`)
            }
      - name: Validate release date
        uses: actions/github-script@v7
        with:
          script: |
            const dateStr = "${{inputs.releaseDate}}";
            if (!/^(\d){8}$/.test(dateStr)) {
              core.setFailed(`invalid date format yyyymmdd: ${dateStr}`)
            }
            const y = dateStr.substr(0,4), m = dateStr.substr(4,2) - 1, d = dateStr.substr(6,2);
            const dt = new Date(y, m, d);
            if (isNaN(dt.getDate())) {
              core.setFailed(`invalid date format yyyymmdd: ${dateStr}`);
            }
            const dy = dt.getFullYear(), dm = ("00" + (dt.getMonth()+1)).slice(-2), dd = ("00" + (dt.getDate())).slice(-2);
            if (dateStr !== dy+dm+dd) {
              core.setFailed(`invalid date format yyyymmdd: ${dateStr}`);
            }

      - name: Set commit user
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name  "[bot] ${GITHUB_ACTOR}"

      - name: Create branch
        id: create-branch
        run: |
          DATETIME_SUFFIX=$(date "+%Y%m%d%H%M")
          branch="${{ inputs.releaseType }}/${{ github.event.inputs.releaseDate }}-${GITHUB_ACTOR}-${DATETIME_SUFFIX}"
          git checkout -b "$branch"
          git commit --allow-empty -m "[${{ inputs.releaseType }}] empty commit for $branch"
          echo "branch=${branch}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
