name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      releaseDate:
        description: "Release Date: YYYYMMDD"
        required: true
      title:
        description: "PR Title"
        required: true

jobs:
  create_release_pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "develop"
          fetch-depth: 0

      - uses: ./.github/workflows/create-release.yml
        id: create-release-branch
        with:
          releaseDate: ${{ inputs.releaseDate }}
          title: ${{ inputs.title }}

      - name: Fetch release PR list
        id: fetch-release-prlist
        run: |
          git log --merges --grep='Merge pull request' --format='%B' remotes/origin/main...develop --pretty="%an|%s" > pr_list.txt
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./.github/scripts/go.mod"
          cache-dependency-path: "./.github/scripts/go.sum"
      - name: Create Release PR Body
        id: create-release-pr-body
        run: |
          echo "prBody<<EOF" >> $GITHUB_OUTPUT
          go run ./main.go createReleasePrBody ../../pr_list.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ./.github/scripts

      - name: Remove temporary file
        run: rm -rf ./pr_list.txt

      - name: Run post release script
        run: |
          SCRIPT_PATH="./.github/config/post-release-script.sh"
          if [ -f "$SCRIPT_PATH" ]; then
            chmod +x "$SCRIPT_PATH"
            ./"$SCRIPT_PATH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release branch
        run: |
          git push origin "${{ steps.create-release-branch.outputs.releaseBranch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release PR
        run: |
          gh pr create --base main --title "${{ github.event.inputs.title }}" --body "${{ steps.create-release-pr-body.outputs.prBody }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
