name: Create Release to Develop PR

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  create_release_to_develop_pr:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set commit user
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name  "[bot] ${GITHUB_ACTOR}"

      - name: Create release to develop branch
        id: create-release-to-develop-branch
        run: |
          releaseBranch="${{ github.event.pull_request.head.ref }}"
          releaseToDevelopBranch="${releaseBranch/release\//release-to-develop/}"
          git checkout -b $releaseToDevelopBranch
          echo "releaseToDevelopBranch=${releaseToDevelopBranch}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run post release script
        run: |
          SCRIPT_PATH="./.github/config/post-release-to-develop-script.sh"
          if [ -f "$SCRIPT_PATH" ]; then
            chmod +x "$SCRIPT_PATH"
            ./"$SCRIPT_PATH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release to develop branch
        run: |
          git push origin "$releaseToDevelopBranch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR to Develop using GitHub CLI
        run: |
          PR_TITLE="[release to develop] ${{ github.event.pull_request.title }}"
          PR_BODY=$'Release to Develop\n- #${{ github.event.pull_request.number }}'
          gh pr create --base develop --title "$PR_TITLE" --body "$PR_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
